spring.application.name=user-service
server.port=8086

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/user-service}
spring.datasource.username=${DB_USERNAME:user_user}
spring.datasource.password=${DB_PASSWORD:user_password}
spring.datasource.driver-class-name=org.postgresql.Driver
