spring.application.name=notification-service
server.port=8083

spring.mongodb.host=${MONGO_HOST:localhost}
spring.mongodb.port=${MONGO_PORT:27017}
spring.mongodb.database=${MONGO_DATABASE:notification-service}
spring.mongodb.username=${MONGO_USERNAME:notification_user}
spring.mongodb.password=${MONGO_PASSWORD:notification_password}
spring.mongodb.authentication-database=${MONGO_AUTH_DATABASE:notification-service}
